//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSULTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONSULTA()
        {
            this.DIAGNOSTICOes = new HashSet<DIAGNOSTICO>();
            this.DOSAGEMs = new HashSet<DOSAGEM>();
        }
    
        public int ID_CONSULTA { get; set; }
        public int ID_FORMULARIO { get; set; }
        public int ID_PACIENTE { get; set; }
        public string NOME_PACIENTE { get; set; }
        public string NOME_RESPONSAVEL { get; set; }
        public System.DateTime DATA_CONSULTA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIAGNOSTICO> DIAGNOSTICOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOSAGEM> DOSAGEMs { get; set; }
        public virtual FORMULARIO FORMULARIO { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
    }
}
