//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIAGNOSTICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIAGNOSTICO()
        {
            this.PARTE_DIAGNOSTICO = new HashSet<PARTE_DIAGNOSTICO>();
            this.RESULTADOes = new HashSet<RESULTADO>();
        }
    
        public int ID_DIAGNOSTICO { get; set; }
        public int ID_CONSULTA { get; set; }
        public System.DateTime DATA_DIAGNOSTICO { get; set; }
        public string NOME_PACIENTE { get; set; }
        public int NUMERO_ITEM { get; set; }
    
        public virtual CONSULTA CONSULTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTE_DIAGNOSTICO> PARTE_DIAGNOSTICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESULTADO> RESULTADOes { get; set; }
    }
}
