//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOSAGEM
    {
        public int ID_DOSAGEM { get; set; }
        public int ID_CONSULTA { get; set; }
        public int ID_PRODUTO { get; set; }
        public string NOME_PACIENTE { get; set; }
        public string NOME_RESPONSAVEL { get; set; }
        public int QUANTIDADE { get; set; }
        public string PRODUTO { get; set; }
        public string DESCRICAO { get; set; }
        public System.DateTime DATA { get; set; }
    
        public virtual CONSULTA CONSULTA { get; set; }
        public virtual PRODUTO PRODUTO1 { get; set; }
    }
}
