//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PIEntities : DbContext
    {
        public PIEntities()
            : base("name=PIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CONSULTA> CONSULTAs { get; set; }
        public virtual DbSet<DIAGNOSTICO> DIAGNOSTICOes { get; set; }
        public virtual DbSet<DOSAGEM> DOSAGEMs { get; set; }
        public virtual DbSet<FORMULARIO> FORMULARIOs { get; set; }
        public virtual DbSet<PACIENTE> PACIENTEs { get; set; }
        public virtual DbSet<PARTE_DIAGNOSTICO> PARTE_DIAGNOSTICO { get; set; }
        public virtual DbSet<PRESCRICAO> PRESCRICAOs { get; set; }
        public virtual DbSet<PRODUTO> PRODUTOes { get; set; }
        public virtual DbSet<RESULTADO> RESULTADOes { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
    }
}
