//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PACIENTE()
        {
            this.CONSULTAs = new HashSet<CONSULTA>();
        }
    
        public int ID_PACIENTE { get; set; }
        public string NOME { get; set; }
        public string SEXO { get; set; }
        public System.DateTime NASCIMENTO { get; set; }
        public string EMDERECO { get; set; }
        public string LOCOMOCAO { get; set; }
        public string RENDA_FAMILIAR { get; set; }
        public string RELIGIAO { get; set; }
        public string FILHOS { get; set; }
        public string ESCOLARIDADE { get; set; }
        public string PROFISSAO { get; set; }
        public string ESTADO_CIVIL { get; set; }
        public string TELEFONE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONSULTA> CONSULTAs { get; set; }
    }
}
