//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUTO()
        {
            this.DOSAGEMs = new HashSet<DOSAGEM>();
        }
    
        public int ID_PRODUTO { get; set; }
        public int ID_USUARIO { get; set; }
        public string NOME { get; set; }
        public int QUANTIDADE { get; set; }
        public System.DateTime VALIDADE { get; set; }
        public string DESCRICAO { get; set; }
        public System.DateTime DATA_ENTRADA { get; set; }
        public System.DateTime DATA_SAIDA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOSAGEM> DOSAGEMs { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
