//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESULTADO
    {
        public int ID_RESULTADO { get; set; }
        public int ID_DIAGNOSTICO { get; set; }
        public int ID_PRESCRICAO { get; set; }
        public string NOME_PACIENTE { get; set; }
        public int NUMERO_ITEM { get; set; }
        public string DESCRICAO { get; set; }
        public System.DateTime DATA { get; set; }
    
        public virtual DIAGNOSTICO DIAGNOSTICO { get; set; }
        public virtual PRESCRICAO PRESCRICAO { get; set; }
    }
}
